version: "3.9"
services:
  postgre:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
  
  redis:
    image: redis:7.0.4-alpine
    ports:
      - 6379:6379
volumes:
  db:
    driver: local